# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='showpicture',
            field=models.CharField(max_length=512, null=True, verbose_name='商品展示图片'),
        ),
    ]
