# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=1000, null=True, verbose_name='列表化储存产品'),
        ),
    ]
