# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190920_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='productnum',
            field=models.IntegerField(null=True, verbose_name='产品数量'),
        ),
    ]
