# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detailaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
